<?php

namespace AppBundle\Repository;

/**
 * PanierContientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanierContientRepository extends \Doctrine\ORM\EntityRepository
{
}
